### ISSUE TITLE
老哥，支付宝的接口调用那里，公钥私钥为空啊

### ISSUE THREAD

**Issue by ghost** [yang-va/onlinestudy#1]
provide_keys和public_keys文件为空，支付宝接口无法调用啊

**Comment by yang-va** [comment]
这个你自己在支付宝开发者平台里注册账号可以免费申请key，为了安全我把key文件内容清空了

**Comment by yang-va** [comment]
> provide_keys和public_keys文件为空，支付宝接口无法调用啊
这个你自己在支付宝开发者平台里注册账号可以免费申请key，为了安全我把key文件内容清空了

**Comment by geekbyter** [comment]
> provide_keys和public_keys文件为空，支付宝接口无法调用啊

这个你自己在支付宝开发者平台里注册账号可以免费申请key，为了安全我把key文件内容清空了
