### ISSUE TITLE
没搞懂，后台这块 ，这个项目是用的admin?还是其他的后台 ，进不了后台

### ISSUE THREAD

**Issue by AIrobot6** [yang-va/onlinestudy#10]

**Comment by geekbyter** [comment]
这个是需要数据配合的，你数据库为空肯定登不上去的，readme文件里我说过了，需要在数据库自建数据，我不提供数据

**Comment by AIrobot6** [comment]
MySQL.sql，我这也没有啊，能不能提供一个，刚上路，不太会弄------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Eeyhan&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月1日(星期三) 下午5:08
收件人:&nbsp;&quot;Eeyhan/onlinestudy&quot;<onlinestudy@noreply.github.com&gt;;
抄送:&nbsp;&quot;AIrobot6&quot;<874060767@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Eeyhan/onlinestudy] 没搞懂，后台这块 ，这个项目是用的admin?还是其他的后台 ，进不了后台 (#10)

**Comment by geekbyter** [comment]
这个我去年做的项目了，数据库文件我刚才找了下已经找不到了。你可以装上mysql数据库，然后随便放几条数据，建几个账号就行了

**Comment by AIrobot6** [comment]
能不能帮我搞一下SQL文件，数据库不太懂，十分感谢，另外能不能加你个联系方式，后面还有项目合作------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Eeyhan&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月1日(星期三) 下午5:41
收件人:&nbsp;&quot;Eeyhan/onlinestudy&quot;<onlinestudy@noreply.github.com&gt;;
抄送:&nbsp;&quot;AIrobot6&quot;<874060767@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Eeyhan/onlinestudy] 没搞懂，后台这块 ，这个项目是用的admin?还是其他的后台 ，进不了后台 (#10)
