### ISSUE TITLE
后台用户无法登录

### ISSUE THREAD

**Issue by leofantast** [yang-va/onlinestudy#2]
您好好，后台管理页面我用root:123455登录不上，去DB里面查了auth_user表是空的，请问怎么添加后台管理的账户呢~

**Comment by geekbyter** [comment]
是123456啊。登不上你就重新创建一个
进入后台的项目目录，用以下命令创建：
python manage.py createsuperuser

根据提示设置好就行了

**Comment by leofantast** [comment]
创建了两个，居然还是报”用户名或密码错误“，方便加个微信吗，还有其他问题想请教下，我微信号：himaguevara

**Comment by geekbyter** [comment]
> 创建了两个，居然还是报”用户名或密码错误“，方便加个微信吗，还有其他问题想请教下，我微信号：himaguevara

数据库源数据自行配置哈，根据自己的数据库表里的账号密码登录验证，我以为你说的django的admin自带的后台。
我重新更新了下项目，相关说明已经给出了

**Comment by leofantast** [comment]
感谢，django自带的管理后台可以进了，但是我在django添加DB_Account数据时报错如下：
![image](https://user-images.githubusercontent.com/20594426/61464614-2497b500-a9a9-11e9-8967-f56cb0fbcf32.png)

可以给我完整的sql建库语句吗，数据不用给，谢啦~ 

还有怎么添加项目管理后台的登录用户呢，我猜是DB_Account表，但level不知道什么值对应项目后台管理员权限

**Comment by geekbyter** [comment]
> 感谢，django自带的管理后台可以进了，但是我在django添加DB_Account数据时报错如下：
> ![image](https://user-images.githubusercontent.com/20594426/61464614-2497b500-a9a9-11e9-8967-f56cb0fbcf32.png)
> 
> 可以给我完整的sql建库语句吗，数据不用给，谢啦~
> 
> 还有怎么添加项目管理后台的登录用户呢，我猜是DB_Account表，但level不知道什么值对应项目后台管理员权限

你在后台根目录迁移数据库会自动创建数据库表的，怎么迁移数据库readme文件里有说明。

管理员的值models表里有说明。

详细的自己研究下django框架吧

**Comment by leofantast** [comment]
好的，我研究研究，3Q~
