### ISSUE TITLE
请问如何进入后台管理呢（不是Django那个），这边尝试了，一直显示“未获取到用户数据，请登录！”

### ISSUE THREAD

**Issue by tenderzada** [yang-va/onlinestudy#9]

**Comment by AIrobot6** [comment]
同样的问题  求帮助 ，

**Comment by geekbyter** [comment]
有问题的朋友，看看你的django2版本，然后在项目最开始的时候是需要自己在数据库内创建账号的，然后才能正常进入后台，再说一次，确实不太方便提供数据，而且我现在要找也找不到了，这是我以前写的项目了，所以请各位自己在数据库内创建账号。不然数据库内没数据，肯定会出现“未获取到用户数据，请登录！”
